[package]
name = "otc_escrow"
type = "contract"
compiler_version = ">=1.0.0"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v1.2.1", directory = "noir-projects/aztec-nr/aztec" }
poseidon = { git = "https:/github.com/noir-lang/poseidon", tag = "v0.1.1" }
# token_contract = { git = "https://github.com/defi-wonderland/aztec-standards", tag = "v1.1.0", directory = "src/token_contract" }
